-- Create database
CREATE DATABASE IF NOT EXISTS SLEEKMART_OMS;

-- Use the database
USE DATABASE SLEEKMART_OMS;

-- Create schema
CREATE SCHEMA IF NOT EXISTS L1_LANDING;

-- CUSTOMERS table
CREATE TABLE IF NOT EXISTS L1_LANDING.CUSTOMERS (
    CUSTOMERID VARCHAR(10),
    FIRSTNAME VARCHAR(50),
    LASTNAME VARCHAR(50),
    EMAIL VARCHAR(100),
    PHONE VARCHAR(50),
    ADDRESS VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(2),
    ZIPCODE VARCHAR(10),
    UPDATED_AT TIMESTAMP_NTZ
);

-- ORDERITEMS table
CREATE TABLE IF NOT EXISTS L1_LANDING.ORDERITEMS (
    ORDERID INT,
    ORDERITEMID INT,
    PRODUCTID INT,
    QUANTITY INT,
    UNITPRICE NUMERIC(10, 2),
    UPDATED_AT TIMESTAMP_NTZ
);

-- ORDERS table
CREATE TABLE IF NOT EXISTS L1_LANDING.ORDERS (
    ORDERID INT,
    ORDERDATE DATE,
    CUSTOMERID VARCHAR(10),
    EMPLOYEEID INT,
    STOREID VARCHAR(10),
    STATUS VARCHAR(2),
    UPDATED_AT TIMESTAMP_NTZ
);