
name: 'oms_analytics'
version: '1.0.0'
config-version: 2


profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" 
clean-targets:  
  - "target"
  - "dbt_packages"

# You can apply hooks at the folder level (applies to all models in the folder)
# or at the individual model level. Hooks can be defined as inline SQL or as macros.

models:
  Customer-Revenue:
    +schema: transform
    +materialized: table
    +transient: false